import discord
import random
import asyncio
import json
import time
from datetime import datetime, timedelta
from discord import app_commands, Color
from discord.ext import commands, tasks
from core.helpers import VN_TZ, ask_ancestor, get_rank_info, txa_embed, number_to_emoji, get_all_rank_names, rainbow_log
from core.format import TXAFormat
from core.database import Database
from core.game_data import CultivationData
from core.roles_config import RoleConfig

class Cultivation(commands.Cog):
    NARRATIVE_STAGES = [
        (0, "🌀 Bắt đầu vận chuyển linh khí, tâm thần dần nhập định..."),
        (20, "⚡ Linh lực cuộn trào trong kinh mạch, mồ hôi bắt đầu thấm đẫm..."),
        (40, "🔥 Đạo lực bùng phát mãnh liệt, đang cố gắng chế ngự kình lực..."),
        (60, "🌊 Khí hải dâng trào, thiên địa linh khí đang hội tụ về cơ thể..."),
        (80, "💎 Gần như chạm tới ngưỡng cửa viên mãn, đạo tâm kiên định tuyệt đối!"),
        (95, "✨ Linh quang lóe sáng! Bí pháp đã hoàn thành 9 phần, chỉ còn chút hơi sức cuối..."),
    ]

    def __init__(self, bot):
        self.bot = bot
        self.db: Database = bot.db

    async def check_auto_role(self, member: discord.Member, layer: int):
        """Tự động cập nhật Role và Nickname dựa trên cảnh giới"""
        rank_name, rank_info = get_rank_info(layer)
        role_data = RoleConfig.get_role_data(rank_name)
        
        # 1. Update Nickname (Prefix)
        # Đặc biệt cho Admin
        is_super = member.id == getattr(self.bot, 'super_admin_id', None)
        is_admin = member.id in getattr(self.bot, 'admin_ids', [])
        
        if is_super:
            prefix = "[Chưởng Môn]"
        elif is_admin:
            prefix = "[Tổ Sư]"
        else:
            prefix = f"[{rank_name}]"
            
        new_nick = member.display_name
        
        # Remove old prefix if exists
        import re
        new_nick = re.sub(r"^\[.*?\]\s*", "", new_nick) 
        new_nick = f"{prefix} {new_nick}"
        
        if len(new_nick) <= 32:
            try:
                if member.display_name != new_nick:
                    # Note: Vẫn sẽ fail nếu là Guild Owner mà bot không đủ quyền, 
                    # nhưng try-except sẽ bắt lỗi này.
                    await member.edit(nick=new_nick)
            except: 
                pass
            
        # 2. Update Roles
        guild = member.guild
        if not guild: return
        current_roles = member.roles
        target_role_name = rank_name
        
        # Find or create role
        target_role = discord.utils.get(guild.roles, name=target_role_name)
        if not target_role:
             try:
                 permissions = discord.Permissions.none()
                 # Apply CUMULATIVE permissions from config (inherit from lower ranks)
                 perm_dict = RoleConfig.get_cumulative_permissions(rank_name)
                 if perm_dict:
                    permissions.update(**perm_dict)
                 
                 target_role = await guild.create_role(
                     name=target_role_name, 
                     color=discord.Color(role_data['color']), 
                     hoist=True, # Show separately
                     permissions=permissions,
                     mentionable=False,
                     reason="Auto-generated by Cultivation Bot"
                 )
             except Exception as e: 
                 rainbow_log(f"Role create error: {e}")
                 pass
        
        if target_role:
            # Luôn kiểm tra và dọn dẹp các role cảnh giới cũ để tránh bị trùng lặp role (như hình đệ tử gửi)
            all_rank_roles = RoleConfig.get_all_roles().keys()
            to_remove = [r for r in current_roles if r.name in all_rank_roles and r.name != target_role_name]
            
            try:
                if to_remove:
                    await member.remove_roles(*to_remove)
                    rainbow_log(f"  [清理] Đã tẩy bỏ {len(to_remove)} role cũ cho {member.display_name}")
                
                if target_role not in current_roles:
                    await member.add_roles(target_role)
                    rainbow_log(f"  [晋升] Đã ban sắc phong {target_role_name} cho {member.display_name}")
            except Exception as e:
                # rainbow_log(f"Role sync error: {e}")
                pass

    async def check_daily_xp_limit(self, user_data, exp_to_add):
        """Kiểm tra giới hạn XP hàng ngày"""
        rank_name, _ = get_rank_info(user_data['layer'])
        role_config = RoleConfig.get_role_data(rank_name)
        limit = role_config.get('daily_xp_limit', 1000)
        
        current_daily = user_data.get('daily_exp', 0)
        
        if current_daily + exp_to_add > limit:
            return False, limit
        return True, limit

    async def update_member_visuals(self, member: discord.Member, layer: int):
        """Update nickname and role based on layer - Tận dụng role cũ nếu có"""
        # This method is now largely superseded by check_auto_role, but kept for compatibility
        # or if specific logic is needed here. For now, it will call check_auto_role.
        await self.check_auto_role(member, layer)

        # --- Gửi DM chúc mừng (Tránh gửi lặp nếu layer mới cập nhật liên tục) ---
        if layer > 1:
            rank_name, rank_info = get_rank_info(layer)
            try:
                embed = txa_embed(
                    "🔥 Đột Phá Cảnh Giới!",
                    f"Chúc mừng đạo hữu **{member.display_name}**!\n"
                    f"Ngươi đã thành công đột phá linh mạch, đạt tới: **{rank_name} (Tầng {layer})**.\n\n"
                    f"Pháp vị của ngươi tại Thiên Lam Tông đã được sắc phong: `{rank_name}`.",
                    rank_info['color']
                )
                embed.set_footer(text="Thiên Đạo ghi danh - Tương lai rộng mở!")
                await member.send(embed=embed)
            except: pass

    @tasks.loop(hours=1)
    async def daily_reminder_task(self):
        """Gửi nhắc nhở điểm danh vào 6h sáng (trước reset 1h)"""
        now = datetime.now(VN_TZ)
        if now.hour != 6: return
        
        users = await self.db.get_all_users()
        today_reset = now.replace(hour=7, minute=0, second=0, microsecond=0)
        today_date = (now - timedelta(hours=7)).strftime("%Y-%m-%d")
        
        # Lấy portal link
        portal_url = None
        target_guild = None
        if self.bot.allowed_guilds:
            target_guild = self.bot.get_guild(self.bot.allowed_guilds[0].id)

        if target_guild:
            if self.bot.allowed_channel_ids:
                # Nếu đã set channel thì về đúng kênh đầu tiên (về đúng)
                portal_url = f"https://discord.com/channels/{target_guild.id}/{self.bot.allowed_channel_ids[0]}"
            else:
                # Nếu chưa set thì random kỳ duyên trong server
                # Tránh kênh report
                target_channels = [
                    c for c in target_guild.text_channels 
                    if c.id != self.bot.report_channel_id and c.permissions_for(target_guild.me).send_messages
                ]
                if target_channels:
                    random_channel = random.choice(target_channels)
                    portal_url = f"https://discord.com/channels/{target_guild.id}/{random_channel.id}"

        for u_data in users:
            if u_data['last_daily_date'] != today_date:
                user = self.bot.get_user(int(u_data['user_id']))
                if not user: continue
                
                streak_emoji = number_to_emoji(u_data['daily_streak'])
                timestamp = int(today_reset.timestamp())
                
                embed = txa_embed("⏰ Nhắc Nhở Điểm Danh", "", Color.orange())
                embed.description = (
                    f"🔥 **Chuỗi điểm danh hiện tại:** {streak_emoji} ngày\n"
                    f"⚠️ **Còn 1 giờ nữa là reset!** (<t:{timestamp}:t>)\n\n"
                    f"💡 Hãy dùng `/daily` ngay để giữ chuỗi streak!\n"
                    f"📈 Streak càng cao, phần thưởng càng lớn!"
                )
                embed.add_field(name="🌀 Cổng Dịch Chuyển", value="Nhấn nút bên dưới để trở về Thiên Lam Tông", inline=False)
                # Dùng TXAFormat để chuẩn hóa thời gian
                time_now = TXAFormat.time(now.hour * 3600 + now.minute * 60 + now.second)
                embed.set_footer(text=f"Pháp thời: {time_now} - THIEN-LAM-LIVE-AI BY TXA!")
                
                view = discord.ui.View()
                if portal_url:
                    view.add_item(discord.ui.Button(label="Trở về Tông Môn", url=portal_url, emoji="⛩️"))
                
                try:
                    await user.send(embed=embed, view=view)
                except: pass

    @daily_reminder_task.before_loop
    async def before_daily_reminder(self):
        await self.bot.wait_until_ready()

    async def cog_load(self):
        self.daily_reminder_task.start()

    async def cog_unload(self):
        self.daily_reminder_task.cancel()

    async def cog_check(self, ctx):
        """Prefix commands are disabled, but keeping for safety"""
        return False

    def interaction_check(self, interaction: discord.Interaction):
        """Kiểm tra kênh và chặn DM cho Slash Commands"""
        if interaction.guild is None:
            return False

        # Nếu không giới hạn kênh thì cho qua hết
        if not self.bot.allowed_channel_ids:
            return True

        if interaction.channel_id not in self.bot.allowed_channel_ids:
            # Gửi tin nhắn ẩn (ephemeral) cho người gõ sai kênh
            asyncio.create_task(interaction.response.send_message(
                "⛩️ **Cấm Chế:** Pháp lệnh này chỉ có thể thi triển tại các kênh chuyên biệt của Thiên Lam Tông!", 
                ephemeral=True
            ))
            return False
        return True

    @app_commands.command(name="start", description="Ghi danh vào Thiên Lam Tông")
    async def start(self, interaction: discord.Interaction):
        await interaction.response.defer(ephemeral=True)
        uid = str(interaction.user.id)
        user = await self.db.get_user(uid)
        if user:
            return await interaction.followup.send("⛩️ Ngươi đã ghi danh rồi, hãy tập trung tu luyện!", ephemeral=True)
        
        msg = await ask_ancestor(
            "Chào đón đệ tử mới.", 
            f"Đệ tử {interaction.user.display_name} nhập môn. Hãy viết 2 câu chào đón trang trọng, thâm sâu."
        )
        
        await self.db.create_user(uid, interaction.user.display_name)
        await self.check_auto_role(interaction.user, 1) # Call new auto role check
        
        embed = txa_embed("⛩️ Thiên Lam Tông - Nhập Môn Ghi Danh", f"**Tổ Sư Từ Dương phán:**\n*\"{msg or 'Đường tu tiên gian nan, đệ tử hãy vững tâm!'}\"*", Color.gold())
        embed.add_field(name="📜 Pháp Lệnh Khai Mở", value="`/nhiem_vu` • `/daily` • `/tu_luyen` • `/info`", inline=False)
        embed.set_footer(text="Pháp môn bí truyền - Chỉ mình ngươi nhìn thấy.")
        await interaction.followup.send(embed=embed, ephemeral=True)

    @app_commands.command(name="admin_sync_roles", description="[Admin] Đồng bộ Role & Nickname cho toàn bộ đệ tử")
    async def admin_sync_roles(self, interaction: discord.Interaction):
        if interaction.user.id not in self.bot.admin_ids:
            return await interaction.response.send_message("🚫 Ngươi không có quyền năng này!", ephemeral=True)
        
        await interaction.response.defer(ephemeral=True)
        
        users = await self.db.get_all_users()
        count = 0
        failed = 0
        
        rainbow_log(f"🔄 Bắt đầu tiến trình đồng bộ {len(users)} đệ tử...")
        for u_data in users:
            uid = int(u_data['user_id'])
            layer = u_data['layer']
            u_name = u_data['name']
            
            try:
                member = interaction.guild.get_member(uid)
                if not member:
                    member = await interaction.guild.fetch_member(uid)
                
                if member:
                    rainbow_log(f"  [+] Đang quy cấp cho: {member.display_name} ({u_name}) - Cấp: {layer}")
                    await self.check_auto_role(member, layer)
                    count += 1
                    await asyncio.sleep(0.5) # Tránh rate limit của Discord
                else:
                    rainbow_log(f"  [-] Không tìm thấy member {uid} ({u_name}) trong server.")
                    failed += 1
            except Exception as e:
                rainbow_log(f"  [!] Lỗi đồng bộ cho {uid} ({u_name}): {e}")
                failed += 1
                
        embed = txa_embed(
            "🔄 Đồng Bộ Hoàn Tất",
            f"Đã cập nhật Role & Nickname cho **{count}** đệ tử.\nThất bại/Không tìm thấy: **{failed}**",
            discord.Color.green()
        )
        await interaction.followup.send(embed=embed)

    @app_commands.command(name="info", description="Xem thông tin tu luyện (Real-time Update)")
    async def info(self, interaction: discord.Interaction, user: discord.Member = None):
        target_user = user or interaction.user
        uid = str(target_user.id)
        
        # Initial defer
        msg = await interaction.response.send_message("🌀 Đang vận chuyển linh lực để soi xét căn cốt...", ephemeral=True)
        
        start_time = time.time()
        # Loop for 3 minutes (180s)
        while time.time() - start_time < 180:
            user_data = await self.db.get_user(uid)
            if not user_data:
                if time.time() - start_time < 5: # First try
                     await interaction.edit_original_response(content="⚠️ Ngươi chưa bước chân vào con đường tu tiên.")
                     return
                break # Stop if user deleted or something

            rank_name, rank_info = get_rank_info(user_data['layer'])
            progress = (user_data['exp'] / user_data['goal']) * 100
            
            # Mission Info
            # Check sect for daily limit
            daily_limit = 10 # Base limit
            sect_bonus_limit = 0
            if user_data.get('sect_id'):
                # Deterministic random based on date + uid
                today_str = datetime.now(VN_TZ).strftime("%Y%m%d")
                # Use a simple hash for reproducibility
                seed_str = f"{uid}{today_str}"
                seed = sum(ord(char) for char in seed_str) % (2**32 - 1) # Simple hash
                
                temp_random = random.Random(seed) # Use a temporary random instance
                sect_bonus_limit = temp_random.randint(3, 7)
                daily_limit += sect_bonus_limit
            
            missions_done = user_data['missions_completed']
            
            # Embed
            embed = txa_embed(
                f"Thông Tin Tu Luyện: {target_user.name}",
                f"Đạo hiệu: **{user_data['name']}**",
                discord.Color.blue()
            )
            embed.set_thumbnail(url=target_user.avatar.url if target_user.avatar else None)
            
            embed.add_field(name="Cảnh Giới", value=f"**{rank_name}** (Tầng {user_data['layer']})", inline=True)
            embed.add_field(name="Linh Lực (EXP)", value=f"`{user_data['exp']:,} / {user_data['goal']:,}` ({progress:.1f}%)\n{TXAFormat.progress_bar(progress)}", inline=True)
            
            sect_text = "Tán Tu"
            if user_data.get('sect_id'):
                 sect_text = f"Đệ Tử Tông Môn (ID: {user_data['sect_id']})" # Simplified for now
                 embed.add_field(name="Tông Môn", value=f"{sect_text}\n*(Có thêm **{random.randint(50, 100)} EXP** khi hoàn thành nhiệm vụ)*", inline=True)
            else:
                 embed.add_field(name="Tông Môn", value=sect_text, inline=True)
            
            # Mission Status
            mission_status = f"Đã hoàn thành: **{missions_done}/{daily_limit}**"
            if sect_bonus_limit > 0:
                mission_status += f"\n*(Đã cộng thêm {sect_bonus_limit} nhiệm vụ tông môn)*"

            current_mission = user_data.get('current_mission')
            if current_mission:
                try:
                    cm = current_mission # current_mission is already a dict
                    end_time = datetime.fromtimestamp(cm['end_time'], tz=VN_TZ)
                    now = datetime.now(VN_TZ)
                    remaining = end_time - now
                    
                    if remaining.total_seconds() > 0:
                        mission_title = next((m['title'] for m in user_data['missions'] if m['id'] == cm['id']), "Nhiệm vụ không rõ")
                        mission_status += f"\n⏳ Đang làm: **{mission_title}**\n⏱️ Còn: `{TXAFormat.remaining_detail(int(remaining.total_seconds()))}`"
                    else:
                        mission_title = next((m['title'] for m in user_data['missions'] if m['id'] == cm['id']), "Nhiệm vụ không rõ")
                        mission_status += f"\n✅ **{mission_title}** đã hoàn thành!\nKiểm tra `/nhiem_vu` để nhận thưởng."
                except Exception as e:
                    rainbow_log(f"Error parsing current_mission in info: {e}")
            
            embed.add_field(name="Nhiệm Vụ Hàng Ngày", value=mission_status, inline=False)
            embed.set_footer(text=f"Cập nhật: {datetime.now(VN_TZ).strftime('%H:%M:%S')} | Tự hủy sau 3 phút")
            
            try:
                await interaction.edit_original_response(content=None, embed=embed)
            except:
                break # Error editing (deleted?)
            
            await asyncio.sleep(5) # Update every 5s
            
        # End loop - Delete
        try:
            await interaction.delete_original_response()
        except: pass

    @app_commands.command(name="daily", description="Nhận quà hàng ngày")
    async def daily(self, interaction: discord.Interaction):
        uid = str(interaction.user.id)
        user = await self.db.get_user(uid)
        if not user:
            embed = txa_embed("⛩️ Thiên Lam Cấm Chế", "Ngươi chưa ghi danh! Hãy dùng `/start` để nhập môn.", discord.Color.red())
            return await interaction.response.send_message(embed=embed, ephemeral=True)
        
        now = datetime.now(VN_TZ)
        reset_hour = 7
        today_reset = now.replace(hour=reset_hour, minute=0, second=0, microsecond=0)
        if now < today_reset: today_reset -= timedelta(days=1)

        # Reset daily_exp if it's a new day for daily_exp tracking
        if user.get('last_daily_exp_reset', 0) < today_reset.timestamp():
            await self.db.update_user(uid, daily_exp=0, last_daily_exp_reset=now.timestamp())
            user['daily_exp'] = 0 # Update local user object for current operation
        
        if user['last_daily'] > today_reset.timestamp():
            await interaction.response.defer(ephemeral=True)
            next_reset = today_reset + timedelta(days=1)
            ts = int(next_reset.timestamp())
            
            # Vòng lặp cập nhật real-time 1s/lần
            # Giới hạn thời gian loop tránh treo tài nguyên (vd: 5 phút)
            loop_end = time.time() + 300 
            
            while time.time() < loop_end:
                now_loop = datetime.now(VN_TZ)
                diff = next_reset - now_loop
                total_seconds = int(diff.total_seconds())
                
                if total_seconds <= 0:
                    break
                
                time_str = TXAFormat.duration_detail(total_seconds)
                
                embed = txa_embed(
                    "⏳ Cấm Chế Thổ Nạp",
                    f"**Đạo hữu hãy tịnh tâm!**\nLinh khí trời đất hiện tại đang khô kiệt, cần thời gian để tái tạo hoàn nguyên.\n\n"
                    f"🌀 **Linh khí hội tụ lại sau:**\n`{time_str}`\n\n"
                    f"⏰ **Thiên thời reset:** <t:{ts}:F> (**<t:{ts}:R>**)",
                    discord.Color.orange()
                )
                embed.set_thumbnail(url="https://hoathinh3d.moi/wp-content/uploads/2023/02/luyen-khi-10-van-nam-300x450.jpg")
                embed.set_footer(text="Thiên Lam Tông - Vạn vật hữu hình, linh khí hữu hạn.")
                
                try:
                    await interaction.edit_original_response(embed=embed)
                except:
                    break # User có thể đã đóng ephemeral message hoặc interaction hết hạn
                
                await asyncio.sleep(1)
            return
        
        await interaction.response.defer(ephemeral=True)
        
        logical_now = now - timedelta(hours=reset_hour)
        today_date = logical_now.strftime("%Y-%m-%d")
        yesterday_date = (logical_now - timedelta(days=1)).strftime("%Y-%m-%d")
        
        streak = user['daily_streak']
        if user['last_daily_date'] == yesterday_date:
            streak += 1
        elif user['last_daily_date'] != today_date:
            streak = 1
            
        reward = 1000 + (streak * 100)

        can_add, limit = await self.check_daily_xp_limit(user, reward)
        if not can_add:
            return await interaction.followup.send(f"🛑 Ngươi đã đạt giới hạn tích lũy linh lực trong ngày (**{limit} EXP**). Hãy nghỉ ngơi, tham gia hoạt động giải trí (như nghe nhạc) để thư giãn!", ephemeral=True)
        
        exp = user['exp'] + reward
        layer = user['layer']
        goal = user['goal']
        daily_exp = user.get('daily_exp', 0) + reward
        
        leveled_up = False
        while exp >= goal:
            exp -= goal
            layer += 1
            goal = layer * 1000
            leveled_up = True
            
        await self.db.update_user(uid, exp=exp, layer=layer, goal=goal, last_daily=now.timestamp(), last_daily_date=today_date, daily_streak=streak, daily_exp=daily_exp)
        if leveled_up: await self.check_auto_role(interaction.user, layer) # Call new auto role check
        
        msg = await ask_ancestor("Ban thưởng điểm danh.", f"Đệ tử nhận {reward} EXP ngày {streak}. Viết 1 câu thâm sâu.")
        
        embed = txa_embed("🎁 Thiên Đạo Ban Phước", f"**Tổ Sư Từ Dương phán:**\n*\"{msg or 'Linh khí quán đỉnh, căn cốt tinh anh!'}\"*", Color.blue())
        embed.add_field(name="📈 Linh Lực Tăng Tiến", value=f"**+{reward} EXP**", inline=True)
        embed.add_field(name="🔥 Đạo Tâm Chuỗi", value=f"**{streak} ngày**", inline=True)
        if leveled_up: embed.add_field(name="🔥 ĐỘT PHÁ CẢNH GIỚI", value=f"Chúc mừng đệ tử đã đột phá đạt tới **Tầng {layer}**!", inline=False)
        
        embed.set_footer(text="Cơ duyên trời ban - Thiên Lam Tông.")
        await interaction.followup.send(embed=embed, ephemeral=True)

    @app_commands.command(name="tu_luyen", description="Tọa thiền luyện khí")
    async def tu_luyen(self, interaction: discord.Interaction):
        uid = str(interaction.user.id)
        user = await self.db.get_user(uid)
        if not user:
            embed = txa_embed("⛩️ Thiên Lam Cấm Chế", "Ngươi chưa ghi danh! Hãy dùng `/start` để nhập môn.", discord.Color.red())
            return await interaction.response.send_message(embed=embed, ephemeral=True)
        
        await interaction.response.defer(ephemeral=True)
        
        duration = random.randint(15, 30)
        start_time = time.time()
        end_time = int(start_time + duration)
        
        embed = txa_embed("🧘 Đang Nhập Định Tu Luyện", f"Thanh tẩy thân thể, hội tụ linh khí trời đất mười vạn năm...\n⏳ Ước tính hoàn tất: <t:{end_time}:t> (<t:{end_time}:R>)", Color.blue())
        bar = TXAFormat.progress_bar(0, 15)
        rem_str = TXAFormat.remaining_detail(duration)
        embed.add_field(name="✨ Tiến Độ", value=f"`{bar}` ({TXAFormat.pad2(0)}%) - {rem_str}")
        msg = await interaction.followup.send(embed=embed, ephemeral=True)
        
        # Cập nhật thanh tiến trình mỗi 1 giây (real-time)
        while True:
            now_t = time.time()
            elapsed = now_t - start_time
            remaining = max(0, int(end_time - now_t))
            percent = min(100, int((elapsed / duration) * 100))
            
            if percent >= 100: break
            
            # Chọn narrative text theo %
            stage_msg = self.NARRATIVE_STAGES[0][1]
            for threshold, text in self.NARRATIVE_STAGES:
                if percent >= threshold:
                    stage_msg = text
            
            # Cập nhật mỗi 1 giây
            bar = TXAFormat.progress_bar(percent, 15)
            rem_str = TXAFormat.remaining_detail(remaining)
            
            embed.description = f"{stage_msg}\n⏳ Ước tính hoàn tất: <t:{end_time}:t> (<t:{end_time}:R>)"
            embed.set_field_at(0, name="✨ Tiến Độ", value=f"`{bar}` ({TXAFormat.pad2(percent)}%) - {rem_str}")
            
            try: await msg.edit(embed=embed)
            except: pass
            
            if percent >= 100: break
            await asyncio.sleep(1)
        
        # Re-fetch user to get latest state
        user = await self.db.get_user(uid)
        gain = random.randint(50, 150) + (user['layer'] * 5)

        can_add, limit = await self.check_daily_xp_limit(user, gain)
        if not can_add:
            res_embed = txa_embed("🛑 Kiệt Sức", f"Ngươi đã đạt giới hạn tích lũy linh lực trong ngày (**{limit} EXP**). Hãy nghỉ ngơi, tham gia hoạt động giải trí (như nghe nhạc) để thư giãn!", Color.orange())
            res_embed.set_footer(text="Công khóa hoàn tất. (Nhấn để đóng)")
            try: await msg.edit(embed=res_embed)
            except: pass
            return
        
        # Bonus Streak (>= 3 ngày)
        bonus_msg = ""
        if user['daily_streak'] >= 3:
            bonus_pct = min(0.5, (user['daily_streak'] // 3) * 0.05)
            bonus_xp = int(gain * bonus_pct)
            gain += bonus_xp
            bonus_msg = f"\n🔥 **Kỳ Duyên Phụ Trợ:** +{bonus_xp} EXP (Streak x{user['daily_streak']})"

        exp = user['exp'] + gain
        layer = user['layer']
        goal = user['goal']
        daily_exp = user.get('daily_exp', 0) + gain
        
        leveled_up = False
        while exp >= goal:
            exp -= goal
            layer += 1
            goal = layer * 1000
            leveled_up = True
            
        await self.db.update_user(uid, exp=exp, layer=layer, goal=goal, daily_exp=daily_exp)
        if leveled_up: await self.check_auto_role(interaction.user, layer) # Call new auto role check
        
        res_text = f"Chu thiên tuần hoàn kết thúc, linh khí đã được luyện hóa.\n📈 Nhận được: **{gain} EXP** linh lực.{bonus_msg}"
        res_embed = txa_embed("🧘 Tu Luyện Hoàn Tất", res_text, Color.green())
        if leveled_up: res_embed.add_field(name="🔥 ĐỘT PHÁ CẢNH GIỚI", value=f"Chúc mừng đệ tử đột phá lên **Tầng {layer}**!")
        
        res_embed.set_footer(text="Công khóa hoàn tất. (Nhấn để đóng)")
        try:
            await msg.edit(embed=res_embed)
        except: pass

    async def generate_missions(self, user):
        """Tạo danh sách nhiệm vụ mới via AI hoặc Fallback"""
        uid = str(user['user_id'])
        is_sect = user.get('sect_id') is not None
        num_missions = 10 if is_sect else 5
        prompt = (
            f"Tạo {num_missions} nhiệm vụ tu tiên ngắn gọn, thâm sâu. "
            "Phân cấp độ khó từ 1 (Dễ) đến 10 (Cực khó). "
            "Phần thưởng (reward) từ 500 đến 10000 tùy độ khó. "
            "Thời gian thực hiện (time) từ 30 đến 300 giây. "
            "Format JSON: [{'id': 1, 'title': '...', 'desc': '...', 'diff': 1-10, 'reward': int, 'time': int}]"
        )
        
        rainbow_log(f"🔮 Đang thỉnh thị Tổ Sư Từ Dương tạo công khóa cho {user['name']}...")
        ai_res = await ask_ancestor("Người tạo nhiệm vụ tu tiên.", prompt, json_mode=True)
        
        missions = []
        try:
            raw_missions = json.loads(ai_res)
            if isinstance(raw_missions, dict): 
                raw_missions = raw_missions.get('missions', [])
                
            for i, m in enumerate(raw_missions):
                diff = m.get('diff', random.randint(1, 10))
                missions.append({
                    "id": i + 1,
                    "title": m.get('title', "Nhiệm vụ vô danh"),
                    "desc": m.get('desc', "Đi tìm cơ duyên..."),
                    "difficulty": diff,
                    "time": m.get('time', diff * 30),
                    "reward": m.get('reward', diff * 500 + random.randint(100, 300)),
                    "success_rate": max(10, 100 - (diff * 8)),
                    "done": False
                })
            rainbow_log(f"✅ AI đã ban xuống {len(missions)} công khóa mới cho {user['name']}.")
        except Exception as e:
            rainbow_log(f"⚠️ Thỉnh thị AI thất bại: {e}. Sử dụng bí tịch Fallback.")
            # Fallback using CultivationData
            num_fallback = 10 if is_sect else 5
            for i in range(num_fallback):
                diff = (i % 5) + 1
                mission_title = CultivationData.get_random_mission()
                missions.append({
                    "id": i + 1,
                    "title": mission_title,
                    "desc": f"Thực hiện {mission_title} để tích lũy kinh nghiệm.",
                    "difficulty": diff,
                    "time": diff * 40,
                    "reward": diff * 350 + random.randint(10, 50), # Random XP base
                    "success_rate": 100 - (diff * 12),
                    "done": False
                })
        
        return missions

    async def finalize_mission(self, interaction: discord.Interaction, uid: str, user: dict, mission_id: int, silent: bool = False):
        """Xử lý kết quả nhiệm vụ bị gián đoạn (silent: chỉ cộng điểm không gửi tin nhắn khôi phục)"""
        if not silent:
            await interaction.response.defer(ephemeral=True)
        
        mission = next((m for m in user['missions'] if m['id'] == mission_id), None)
        if not mission:
            await self.db.update_user(uid, current_mission=None)
            return
        
        # Re-fetch user để đảm bảo data mới nhất
        user = await self.db.get_user(uid)
        if not user or not user.get('current_mission'): return

        success = random.randint(1, 100) <= mission['success_rate']
        
        # Xóa current_mission TRƯỚC khi update các cái khác
        await self.db.update_user(uid, current_mission=None)
        
        if success:
            new_missions = user['missions']
            for m in new_missions:
                if m['id'] == mission['id']: m['done'] = True
            
            reward = mission['reward']

            can_add, limit = await self.check_daily_xp_limit(user, reward)
            if not can_add:
                if not silent:
                    return await interaction.followup.send(f"🛑 Ngươi đã đạt giới hạn tích lũy linh lực trong ngày (**{limit} EXP**). Hãy nghỉ ngơi, tham gia hoạt động giải trí (như nghe nhạc) để thư giãn!", ephemeral=True)
                return # If silent, just return without adding XP

            # Sect Bonus XP
            if user.get('sect_id'):
                sect_bonus_xp = random.randint(50, 100)
                reward += sect_bonus_xp
                
            bonus_msg = ""
            if user['daily_streak'] >= 3:
                bonus_pct = min(0.5, (user['daily_streak'] // 3) * 0.05)
                bonus_xp = int(reward * bonus_pct)
                reward += bonus_xp
                bonus_msg = f"\n🔥 **Hào Quang Streak:** +{bonus_xp} EXP"

            exp = user['exp'] + reward
            layer = user['layer']
            goal = user['goal']
            daily_exp = user.get('daily_exp', 0) + reward
            leveled_up = False
            while exp >= goal:
                exp -= goal
                layer += 1
                goal = max(layer * 1000, 200)
                leveled_up = True
            
            await self.db.update_user(uid, missions=new_missions, missions_completed=user['missions_completed'] + 1, exp=exp, layer=layer, goal=goal, daily_exp=daily_exp)
            if leveled_up: await self.check_auto_role(interaction.user, layer) # Call new auto role check
            
            if not silent:
                res_embed = txa_embed(
                    "✅ Công Khóa Đã Hoàn Tất", 
                    f"Nhiệm vụ **{mission['title']}** đã hoàn thành viên mãn!\n"
                    f"📈 Nhận được: **{reward} EXP** linh lực.{bonus_msg}", 
                    Color.green()
                )
                if leveled_up: res_embed.add_field(name="🔥 ĐỘT PHÁ CẢNH GIỚI", value=f"Ngươi đã đạt tới **Tầng {layer}**!")
                await interaction.followup.send(embed=res_embed, ephemeral=True)
        else:
            # Ghi lại thời gian thất bại để hồi phục (3 phút)
            new_missions = user['missions']
            for m in new_missions:
                if m['id'] == mission['id']:
                    m['retry_time'] = int(time.time() + 180)
            await self.db.update_user(uid, missions=new_missions)

            if not silent:
                res_embed = txa_embed(
                    "❌ Tâm Ma Xâm Nhập", 
                    f"Nhiệm vụ **{mission['title']}** đã thất bại do tâm thần bất ổn.\n"
                    f"⏱️ Ngươi cần **3 phút** để tịnh tâm phục hồi trước khi thử lại nhiệm vụ này.", 
                    Color.red()
                )
                await interaction.followup.send(embed=res_embed, ephemeral=True)

    def get_diff_name(self, diff: int):
        """Chuyển độ khó thành danh xưng tu tiên"""
        data = {
            1: "🟢 Thuận Buồm Xuôi Gió",
            2: "🟡 Sóng Yên Biển Lặng",
            3: "🟠 Phong Ba Bão Táp",
            4: "🔴 Kẻ Sống Người Chết",
            5: "💀 Cửu Tử Nhất Sinh"
        }
        return data.get(diff, "❓ Vô Định")

    @app_commands.command(name="nhiem_vu", description="Xem danh sách nhiệm vụ hôm nay")
    async def nhiem_vu(self, interaction: discord.Interaction):
        await interaction.response.defer(ephemeral=True)
        uid = str(interaction.user.id)
        user = await self.db.get_user(uid)
        if not user: return await interaction.followup.send("⛩️ Ngươi chưa ghi danh!", ephemeral=True)
        
        now = datetime.now(VN_TZ)
        # Reset lúc 7h sáng
        reset_hour = 7
        today_reset = now.replace(hour=reset_hour, minute=0, second=0, microsecond=0)
        if now < today_reset: today_reset -= timedelta(days=1)
        
        # Reset daily exp if needed
        if user.get('last_daily_exp_reset', 0) < today_reset.timestamp():
            await self.db.update_user(uid, daily_exp=0, last_daily_exp_reset=now.timestamp())
            user['daily_exp'] = 0 # Update local user object for current operation
        
        # Calculate dynamic daily limit
        daily_limit = 10 # Base limit
        sect_bonus_limit = 0
        if user.get('sect_id'):
            today_str = datetime.now(VN_TZ).strftime("%Y%m%d")
            seed_str = f"{uid}{today_str}"
            seed = sum(ord(char) for char in seed_str) % (2**32 - 1)
            temp_random = random.Random(seed)
            sect_bonus_limit = temp_random.randint(3, 7)
            daily_limit += sect_bonus_limit
        
        # Kiểm tra reset nhiệm vụ
        should_refresh = False
        if user['last_mission_reset'] < today_reset.timestamp():
            should_refresh = True
        elif user['missions_completed'] >= daily_limit: # Check against dynamic limit
            # If all missions are done and limit reached, no refresh
            pass
        elif all(m['done'] for m in user['missions']):
            # If all current missions are done but limit not reached, refresh
            should_refresh = True
            rainbow_log(f"🔄 {user['name']} đã hoàn tất đợt công khóa, đang làm mới...")

        if should_refresh:
            missions = await self.generate_missions(user)
            await self.db.update_user(uid, missions=missions, last_mission_reset=now.timestamp(), missions_completed=0) # Reset missions_completed on new day
            user['missions'] = missions
            user['missions_completed'] = 0 # Update local user object

        # Kiểm tra nhiệm vụ đang làm (Đồng bộ ID)
        current_mission_id = None
        if user.get('current_mission'):
            curr = user['current_mission']
            remaining = int(curr['end_time'] - time.time())
            if remaining > 0:
                current_mission_id = int(curr['id'])
            else:
                # Tự động finalize nếu đã xong
                asyncio.create_task(self.finalize_mission(interaction, uid, user, int(curr['id']), silent=True))

        async def build_desc(curr_rem=0):
            d = f"📊 **Tiến độ hôm nay:** `{user['missions_completed']}/{daily_limit}` công khóa\n"
            if sect_bonus_limit > 0:
                d += f"*(Đã cộng thêm {sect_bonus_limit} nhiệm vụ tông môn)*\n"
            d += "\n"

            for m in user['missions']:
                m_id = int(m['id'])
                if m_id == current_mission_id and curr_rem > 0:
                    status = "⚔️"  # Đang làm
                    time_info = f" • **Còn {TXAFormat.remaining_detail(curr_rem)}**"
                elif m['done']:
                    status = "✅"  # Hoàn thành
                    time_info = ""
                elif m.get('retry_time') and time.time() < m['retry_time']:
                    status = "❌"  # Thất bại - Đang cooldown
                    rem = int(m['retry_time'] - time.time())
                    time_info = f" • **Thử lại sau {rem}s**"
                else:
                    status = "⏳"  # Chưa làm
                    time_info = ""
                
                diff_text = self.get_diff_name(m['difficulty'])
                d += f"{status} **[{m['id']}] {m['title']}**{time_info}\n"
                d += f"└ *Độ khó: {diff_text}*\n"
                d += f"└ *Thưởng: {TXAFormat.number(m['reward'])} Linh Lực • TG: {TXAFormat.remaining_detail(m['time'])} • Thành công: {m['success_rate']}%*\n\n"
            return d

        curr_rem = 0
        if current_mission_id:
            curr_rem = int(user['current_mission']['end_time'] - time.time())

        desc = await build_desc(curr_rem)
        embed = txa_embed("📜 Thiên Lam Linh Bảng - Nhiệm Vụ", desc, Color.blue())
        embed.set_footer(text="Sử dụng /lam_nhiem_vu [id] để tiếp nhận cơ duyên.")
        msg = await interaction.followup.send(embed=embed, ephemeral=True)

        if current_mission_id and curr_rem > 0:
            loop_end = time.time() + 300
            while time.time() < loop_end:
                now_t = time.time()
                curr_rem = int(user['current_mission']['end_time'] - now_t)
                
                if curr_rem <= 0:
                    # Cập nhật lần cuối khi xong
                    embed.description = await build_desc(0)
                    try: await msg.edit(embed=embed)
                    except: pass
                    break
                
                embed.description = await build_desc(curr_rem)
                try: await msg.edit(embed=embed)
                except: break
                await asyncio.sleep(1)

    @app_commands.command(name="lam_nhiem_vu", description="Bắt đầu thực hiện nhiệm vụ")
    @app_commands.describe(mission_id="ID của nhiệm vụ trong danh sách của ngươi")
    async def lam_nhiem_vu(self, interaction: discord.Interaction, mission_id: int):
        uid = str(interaction.user.id)
        user = await self.db.get_user(uid)
        if not user:
            embed = txa_embed("⛩️ Thiên Lam Cấm Chế", "Ngươi chưa ghi danh! Hãy dùng `/start`.", discord.Color.red())
            return await interaction.response.send_message(embed=embed, ephemeral=True)
        
        # Calculate dynamic daily limit
        daily_limit = 10 # Base limit
        if user.get('sect_id'):
            today_str = datetime.now(VN_TZ).strftime("%Y%m%d")
            seed_str = f"{uid}{today_str}"
            seed = sum(ord(char) for char in seed_str) % (2**32 - 1)
            temp_random = random.Random(seed)
            daily_limit += temp_random.randint(3, 7)

        if user['missions_completed'] >= daily_limit:
            embed = txa_embed("⚠️ Kiệt Sức", "Ngươi đã kiệt sức! Hôm nay làm đủ nhiệm vụ rồi, hãy nghỉ ngơi hoặc bế quan dưỡng thần.", discord.Color.orange())
            return await interaction.response.send_message(embed=embed, ephemeral=True)

        if mission_id == -1:
            embed = txa_embed("⛩️ Tổ Sư Nhắc Nhở", "Hãy kiểm tra lại danh sách nhiệm vụ của ngươi!", discord.Color.orange())
            return await interaction.response.send_message(embed=embed, ephemeral=True)

        mission = next((m for m in user['missions'] if m['id'] == mission_id), None)
        if not mission:
            embed = txa_embed("❌ Lỗi Thần Thức", "Không tìm thấy công khóa này trong tàng thư!", discord.Color.red())
            return await interaction.response.send_message(embed=embed, ephemeral=True)
        if mission['done']:
            embed = txa_embed("✅ Công Khóa Hoàn Tất", "Công khóa này ngươi đã hoàn tất viên mãn!", discord.Color.green())
            return await interaction.response.send_message(embed=embed, ephemeral=True)

        # Kiểm tra cooldown thất bại
        if mission.get('retry_time') and time.time() < mission['retry_time']:
            remaining = int(mission['retry_time'] - time.time())
            embed = txa_embed(
                "⏳ Tâm Linh Đang Phục Hồi",
                f"Ngươi đã thất bại nhiệm vụ **{mission['title']}**.\n"
                f"⏱️ Cần nghỉ ngơi thêm: **{remaining} giây**.",
                discord.Color.red()
            )
            return await interaction.response.send_message(embed=embed, ephemeral=True)

        if user['current_mission']:
            # Kiểm tra nếu đang trong tiến trình
            curr = user['current_mission']
            remaining = int(curr['end_time'] - time.time())
            if remaining > 0:
                # Lấy tên nhiệm vụ đang làm
                curr_mission = next((m for m in user['missions'] if m['id'] == curr['id']), None)
                curr_name = curr_mission['title'] if curr_mission else "Không rõ"
                
                embed = txa_embed(
                    "⏳ Công Khóa Đang Tiến Hành",
                    f"Ngươi đang dốc sức thực hiện: **{curr_name}**\n\n"
                    f"⏱️ Hoàn thành sau: <t:{int(curr['end_time'])}:R>\n"
                    f"📊 Thời gian còn lại: **{TXAFormat.remaining_detail(remaining)}**",
                    discord.Color.orange()
                )
                embed.set_footer(text="Hãy kiên nhẫn, đạo tâm sẽ dẫn đạo.")
                return await interaction.response.send_message(embed=embed, ephemeral=True)
            else:
                # Nhiệm vụ đã xong nhưng chưa được xử lý (bot restart giữa chừng)
                # Xử lý kết quả ngay
                await self.finalize_mission(interaction, uid, user, curr['id'])
                return

        await interaction.response.defer(ephemeral=True)
        
        # Bắt đầu làm
        start_t = time.time()
        end_time = int(start_t + mission['time'])
        await self.db.update_user(uid, current_mission={"id": mission['id'], "end_time": end_time})
        
        # Để tránh việc hiện "2 phút trước" khi máy chủ lệch giờ, ta dùng text thủ công bên dưới kết hợp timestamp
        embed = txa_embed(f"⚔️ Tiếp Nhận: {mission['title']}", f"{self.NARRATIVE_STAGES[0][1]}\n⏳ Ước tính hoàn tất: <t:{end_time}:t> (<t:{end_time}:R>)", Color.purple())
        bar = TXAFormat.progress_bar(0, 15)
        rem_str = TXAFormat.remaining_detail(mission['time'])
        embed.add_field(name="✨ Tiến Độ", value=f"`{bar}` ({TXAFormat.pad2(0)}%) - {rem_str}")
        msg = await interaction.followup.send(embed=embed, ephemeral=True)
        
        # Cập nhật progress mỗi 1 giây (real-time)
        last_stage_msg = self.NARRATIVE_STAGES[0][1]
        while True:
            now_t = time.time()
            elapsed = now_t - start_t
            remaining = max(0, int(end_time - now_t))
            percent = min(100, int((elapsed / mission['time']) * 100))
            
            if percent >= 100: break
            
            # Chọn narrative text theo %
            stage_msg = self.NARRATIVE_STAGES[0][1]
            for threshold, text in self.NARRATIVE_STAGES:
                if percent >= threshold:
                    stage_msg = text
            
            bar = TXAFormat.progress_bar(percent, 15)
            rem_str = TXAFormat.remaining_detail(remaining)
            
            # Chỉ cập nhật nếu có sự thay đổi đáng kể hoặc tin nhắn mới
            embed.description = f"{stage_msg}\n⏳ Ước tính hoàn tất: <t:{end_time}:t> (<t:{end_time}:R>)"
            embed.set_field_at(0, name="✨ Tiến Độ", value=f"`{bar}` ({TXAFormat.pad2(percent)}%) - {rem_str}")
            
            try: await msg.edit(embed=embed)
            except: pass
            
            if percent >= 100: break
            await asyncio.sleep(1)

        # Xử lý kết quả
        user = await self.db.get_user(uid) # Re-fetch
        success = random.randint(1, 100) <= mission['success_rate']
        
        # Xóa current_mission
        await self.db.update_user(uid, current_mission=None)
        
        if success:
            # ... (giữ nguyên logic thành công) ...
            # Mark done in list
            new_missions = user['missions']
            for m in new_missions:
                if m['id'] == mission['id']: m['done'] = True
            
            reward = mission['reward']

            can_add, limit = await self.check_daily_xp_limit(user, reward)
            if not can_add:
                 return await interaction.followup.send(f"🛑 Ngươi đã đạt giới hạn tích lũy linh lực trong ngày (**{limit} EXP**). Hãy nghỉ ngơi, tham gia hoạt động giải trí (như nghe nhạc) để thư giãn!", ephemeral=True)
            
            # Sect Bonus XP
            if user.get('sect_id'):
                sect_bonus_xp = random.randint(50, 100)
                reward += sect_bonus_xp
            
            # Bonus streak
            bonus_msg = ""
            if user['daily_streak'] >= 3:
                bonus_pct = min(0.5, (user['daily_streak'] // 3) * 0.05)
                bonus_xp = int(reward * bonus_pct)
                reward += bonus_xp
                bonus_msg = f"\n🔥 **Hào Quang Streak:** +{bonus_xp} EXP"

            exp = user['exp'] + reward
            layer = user['layer']
            goal = user['goal']
            leveled_up = False
            while exp >= goal:
                exp -= goal
                layer += 1
                goal = max(layer * 1000, 200)
                leveled_up = True
            
            await self.db.update_user(uid, missions=new_missions, missions_completed=user['missions_completed'] + 1, exp=exp, layer=layer, goal=goal)
            if leveled_up: await self.check_auto_role(interaction.user, layer) # Call new auto role check
            
            res_embed = txa_embed("✅ Cơ Duyên Viên Mãn", f"Chúc mừng! Ngươi đã hoàn thành **{mission['title']}**.\n📈 Nhận được: **{reward} EXP** linh lực.{bonus_msg}", Color.green())
            if leveled_up: res_embed.add_field(name="🔥 ĐỘT PHÁ CẢNH GIỚI", value=f"Ngươi đã đạt tới **Tầng {layer}**!")
        else:
            # Ghi lại thời gian thất bại (3 phút)
            new_missions = user['missions']
            for m in new_missions:
                if m['id'] == mission['id']:
                    m['retry_time'] = int(time.time() + 180)
            await self.db.update_user(uid, missions=new_missions)
            
            res_embed = txa_embed("❌ Tâm Ma Xâm Nhập", f"Đáng tiếc! Ngươi đã thất bại trong nhiệm vụ **{mission['title']}**.\n⏱️ Cần tịnh tâm trong **3 phút** để có thể thử lại.", Color.red())

        await msg.edit(embed=res_embed)

    @lam_nhiem_vu.autocomplete("mission_id")
    async def _mission_autocomplete(self, interaction: discord.Interaction, current: str):
        user = await self.db.get_user(str(interaction.user.id))
        if not user or not user.get('missions'): return []
        
        # Calculate dynamic daily limit
        daily_limit = 10 # Base limit
        if user.get('sect_id'):
            today_str = datetime.now(VN_TZ).strftime("%Y%m%d")
            seed_str = f"{str(interaction.user.id)}{today_str}"
            seed = sum(ord(char) for char in seed_str) % (2**32 - 1)
            temp_random = random.Random(seed)
            daily_limit += temp_random.randint(3, 7)

        choices = []
        pending = [m for m in user['missions'] if not m['done']]
        
        if user['missions_completed'] >= daily_limit:
            return [app_commands.Choice(name="💤 Ngươi đã kiệt sức! Hãy nghỉ ngơi đến ngày mai.", value=-1)]
            
        if not pending:
            return [app_commands.Choice(name="✨ Đã xong đợt này! Dùng /nhiem_vu để nhận đợt tiếp theo.", value=-1)]

        for m in pending:
            title = f"{m['id']}. {m['title']} ({self.get_diff_name(m['difficulty'])})"
            if current.lower() in title.lower():
                choices.append(app_commands.Choice(name=title, value=m['id']))
        return choices[:25]

    @app_commands.command(name="bxh", description="Bảng xếp hạng Thiên Lam Tông")
    async def bxh(self, interaction: discord.Interaction):
        await interaction.response.defer(ephemeral=True)
        top = await self.db.get_top_users(10)
        
        desc = "```ansi\n"
        desc += "\u001b[1;33m┏━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓\u001b[0m\n"
        desc += "\u001b[1;33m┃ HẠNG ┃      ĐẠO HỮU      ┃ CẢNH GIỚI ┃   TU VI   ┃\u001b[0m\n"
        desc += "\u001b[1;33m┣━━━━╋━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫\u001b[0m\n"
        
        for i, u in enumerate(top, 1):
            rank_name, info = get_rank_info(u['layer'])
            # Cắt ngắn tên nếu quá dài
            name = (u['name'][:15] + '..') if len(u['name']) > 17 else u['name']
            
            # Emojis và màu sắc cho Top 3
            if i == 1: medal, color = "🥇", "\u001b[1;33m" # Gold
            elif i == 2: medal, color = "🥈", "\u001b[1;37m" # Silver
            elif i == 3: medal, color = "🥉", "\u001b[1;31m" # Bronze
            else: medal, color = f"{i:2}", "\u001b[0;37m"
            
            exp_str = f"{u['exp']:,}"
            desc += f"┃ {medal} ┃ {color}{name:<19}\u001b[0m ┃ Tầng {u['layer']:3} ┃ {exp_str:>9} ┃\n"
            
        desc += "\u001b[1;33m┗━━━━┻━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━┻━━━━━━━━━━━┛\u001b[0m\n"
        desc += "```"
            
        embed = txa_embed("📊 Thiên Lam Tu Vi Bảng", desc or "Chư thiên chưa có ai ghi danh!", Color.gold())
        embed.set_thumbnail(url="https://hoathinh3d.moi/wp-content/uploads/2023/02/luyen-khi-10-van-nam-300x450.jpg")
        embed.add_field(name="✨ Pháp Tắc", value="Đạo hữu có tu vi thâm hậu nhất sẽ đứng đầu thiên bảng.", inline=False)
        embed.set_footer(text="Thần bảng phong vân - Thiên Lam Tông.")
        await interaction.followup.send(embed=embed, ephemeral=True)

async def setup(bot):
    await bot.add_cog(Cultivation(bot))
